"""
asset_version_postprocess.py

Post-processes a Blender remote asset library listing (already generated by
`blender -b -c asset_listing generate .`) to compute correct `bl_versions`
(min/until) ranges from a *folder-based* versioning scheme, instead of
relying on files sitting side-by-side with an "@bMAJOR_MINOR" filename
marker, which is what Blender's built-in generator itself understands.

Expected layout, e.g.:

    5.2/Bradley Preset@b5_2.blend
    5.3/Bradley Preset@b5_3.blend

The version folder ("5.2", "5.3") is authoritative for min/until. Any
"@bX_Y" marker left in the filename is treated as a human-readable label
only -- this script doesn't need it, and just warns (without failing) if
it disagrees with the folder.

Can be used two ways:
  1. Imported: `from asset_version_postprocess import process_library`
  2. Standalone: `python asset_version_postprocess.py /path/to/library`

ASSUMPTIONS, confirmed against a real generated assets-*.json sample:
  - Index file lives at     <root>/_v1/asset-index.json
  - Top-level meta lives at <root>/_asset-library-meta.json
  - AssetLibraryIndexV1 has a "pages" list of {"url", "hash"}
  - Each page JSON has "assets": [...] and "files": [...]
  - Each asset has "files": [<relpath>, ...] and "bl_versions": {...}
  - Each file entry has "path", "hash", "blender_version" (e.g. "5.3.19")
  - Hash strings look like "SHA256:<hex>"
"""

from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path
from typing import Callable
from urllib.parse import unquote

API_SUBDIR = "_v1"
INDEX_FILENAME = "asset-index.json"
META_FILENAME = "_asset-library-meta.json"
API_VERSION_KEY = "v1"

_DIRNAME_RE = re.compile(r'(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)')
_MARKER_RE = re.compile(r'(.*?)@b(0|[1-9][0-9]*)_(0|[1-9][0-9]*)', re.IGNORECASE)

BlenderVersion = tuple[int, int]
LogFn = Callable[[str], None]


def _hash_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 16), b""):
            h.update(chunk)
    return f"SHA256:{h.hexdigest()}"


def _version_str(v: BlenderVersion) -> str:
    return f"{v[0]}.{v[1]}"


def _dir_version(relpath: Path) -> BlenderVersion | None:
    """Version from the immediate parent folder, e.g. '5.3/chair.blend' -> (5, 3)."""
    m = _DIRNAME_RE.fullmatch(relpath.parent.name)
    if not m:
        return None
    return (int(m.group(1)), int(m.group(2)))


def _cluster_key(relpath: Path, log: LogFn) -> Path:
    """Base identity of a file, ignoring its version folder and @bX_Y marker.

    '5.3/Bradley Preset@b5_3.blend' -> 'Bradley Preset.blend'
    """
    stem = relpath.stem
    m = _MARKER_RE.fullmatch(stem)
    marker_version: BlenderVersion | None = None
    if m and m.group(1):
        stem = m.group(1)
        marker_version = (int(m.group(2)), int(m.group(3)))

    dv = _dir_version(relpath)
    if dv is not None and marker_version is not None and dv != marker_version:
        log(f"warning: {relpath}: filename marker {_version_str(marker_version)} "
            f"disagrees with folder version {_version_str(dv)} (folder wins)")

    parent = relpath.parent.parent if dv is not None else relpath.parent
    return parent / f"{stem}{relpath.suffix}"


def _compute_min_until(
    all_relpaths: list[Path], log: LogFn,
) -> dict[Path, tuple[BlenderVersion, BlenderVersion | None]]:
    clusters: dict[Path, list[tuple[BlenderVersion, Path]]] = {}
    for rp in all_relpaths:
        dv = _dir_version(rp)
        if dv is None:
            log(f"warning: {rp} has no 'MAJOR.MINOR' parent folder, leaving its bl_versions untouched")
            continue
        key = _cluster_key(rp, log)
        clusters.setdefault(key, []).append((dv, rp))

    result: dict[Path, tuple[BlenderVersion, BlenderVersion | None]] = {}
    for members in clusters.values():
        members.sort(key=lambda t: t[0])
        for i, (ver, rp) in enumerate(members):
            until = None
            for next_ver, _ in members[i + 1:]:
                if next_ver != ver:
                    until = next_ver
                    break
            result[rp] = (ver, until)
    return result


def _load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _save_json(path: Path, data: dict) -> None:
    path.write_text(json.dumps(data, indent=2), encoding="utf-8")


def process_library(root: Path, dry_run: bool = False, log: LogFn = print) -> int:
    """Rewrite bl_versions in-place based on folder structure.

    Returns the number of pages that were (or, in dry-run mode, would be)
    changed. Raises FileNotFoundError if the library hasn't been generated
    by Blender yet.
    """
    root = root.resolve()
    index_path = root / API_SUBDIR / INDEX_FILENAME
    meta_path = root / META_FILENAME

    if not index_path.exists():
        raise FileNotFoundError(
            f"{index_path} not found -- run the Blender asset_listing generator first"
        )

    index = _load_json(index_path)
    page_entries = index["pages"]
    page_paths = [root / unquote(p["url"]) for p in page_entries]

    # Pass 1: gather every referenced .blend relpath across ALL pages, since a
    # file's 'until' can depend on a sibling that lives on a different page.
    all_relpaths: list[Path] = []
    page_cache: dict[Path, dict] = {}
    for pp in page_paths:
        data = _load_json(pp)
        page_cache[pp] = data
        for f in data.get("files", []):
            all_relpaths.append(Path(f["path"]))

    version_map = _compute_min_until(all_relpaths, log)

    # Real internal Blender version per file, reused to reproduce the
    # original generator's "min = max(folder, actual)" safety check.
    file_actual_version: dict[Path, BlenderVersion] = {}
    for data in page_cache.values():
        for f in data.get("files", []):
            bv = f.get("blender_version") or ""
            if bv:
                parts = bv.split(".")
                file_actual_version[Path(f["path"])] = (int(parts[0]), int(parts[1]))

    # Pass 2: rewrite bl_versions on every asset.
    changed_pages: list[Path] = []
    for pp, data in page_cache.items():
        page_changed = False
        for asset in data.get("assets", []):
            files = asset.get("files") or []
            if not files:
                continue
            rp = Path(files[0])
            if rp not in version_map:
                continue

            folder_min, until = version_map[rp]
            actual = file_actual_version.get(rp)
            resolved_min = max(folder_min, actual) if actual else folder_min

            if actual and actual > folder_min:
                log(f"warning: {rp} was written with Blender {_version_str(actual)}, "
                    f"newer than its folder version {_version_str(folder_min)}")

            new_bl_versions = {"min": _version_str(resolved_min)}
            if until and until > resolved_min:
                new_bl_versions["until"] = _version_str(until)
            elif until:
                log(f"warning: {rp}: computed 'until' {_version_str(until)} is not after "
                    f"'min' {_version_str(resolved_min)}, dropping 'until'")

            if asset.get("bl_versions") != new_bl_versions:
                asset["bl_versions"] = new_bl_versions
                page_changed = True

        if page_changed:
            changed_pages.append(pp)

    if not changed_pages:
        log("Version post-processing: nothing to change.")
        return 0

    if dry_run:
        log(f"Version post-processing (dry run): {len(changed_pages)} page(s) would change:")
        for pp in changed_pages:
            log(f"  {pp.relative_to(root)}")
        return len(changed_pages)

    # Pass 3: write changed pages, then cascade hash updates: page -> index -> meta.
    for pp in changed_pages:
        _save_json(pp, page_cache[pp])

    index_changed = False
    for entry, pp in zip(page_entries, page_paths):
        if pp in changed_pages:
            entry["hash"] = _hash_file(pp)
            index_changed = True

    if index_changed:
        _save_json(index_path, index)

        if meta_path.exists():
            meta = _load_json(meta_path)
            api_versions = meta.get("api_versions", {})
            if API_VERSION_KEY in api_versions:
                api_versions[API_VERSION_KEY]["hash"] = _hash_file(index_path)
                _save_json(meta_path, meta)
            else:
                log(f"warning: {meta_path} has no '{API_VERSION_KEY}' entry under "
                    f"'api_versions' -- its hash was not updated")
        else:
            log(f"warning: {meta_path} not found -- its hash was not updated")

    log(f"Version post-processing: updated {len(changed_pages)} page(s), re-hashed index and meta.")
    return len(changed_pages)


def _main() -> None:
    import argparse

    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument("repository", type=Path,
                     help="Asset library root (the same folder you ran 'asset_listing generate' on)")
    ap.add_argument("--dry-run", action="store_true",
                     help="Print what would change without writing anything")
    args = ap.parse_args()

    try:
        process_library(args.repository, dry_run=args.dry_run)
    except FileNotFoundError as ex:
        raise SystemExit(f"error: {ex}")


if __name__ == "__main__":
    _main()
